WVSData <- read.csv(file = "C:\\Users\\cstan511\\Downloads\\WV_US.csv",header=TRUE,sep=",")
summary(WVSData$V23)
str(WVSData)
myReg=lm(v23-v59,WVSData)
summary(myReg)
summary(WVSData$V23)
hist(WVSData$V23)
